Move all services to /service
This concerns all services, a.k.a drivers, filesystem drivers, network
(inet, lwip, uds) servers, and the system servers.

Change-Id: I626fd15c795e15af42df2d10d47fb4a703665d63

diff --git a/minix/drivers/storage/ramdisk/rc b/minix/drivers/storage/ramdisk/rc
--- a/minix/drivers/storage/ramdisk/rc
+++ b/minix/drivers/storage/ramdisk/rc
@@ -6,17 +6,17 @@ exec 2>/dev/log
 exec </dev/null
 
 FSCK=/bin/fsck_mfs
-ACPI=/usr/sbin/acpi
+ACPI=/service/acpi
 
 if [ X`/bin/sysenv arch` = Xi386 ]
 then	if [ -e $ACPI -a -n "`sysenv acpi`" ]
 	then
 		/bin/service -c up $ACPI
 	fi
-	/bin/service -c up /usr/sbin/pci
+	/bin/service -c up /service/pci
 
-	/bin/service -c up /sbin/input -dev /dev/kbdmux
-	/bin/service -c up /sbin/pckbd
+	/bin/service -c up /service/input -dev /dev/kbdmux
+	/bin/service -c up /service/pckbd
 
 	# Start procfs so we can access /proc/pci
 	mount -t procfs none /proc >/dev/null
@@ -30,27 +30,27 @@ then	if [ -e $ACPI -a -n "`sysenv acpi`" ]
 		virtio_blk=yes
         fi
 
-	/bin/service -cn up /sbin/floppy -dev /dev/fd0
+	/bin/service -cn up /service/floppy -dev /dev/fd0
 	if [ X`/bin/sysenv ahci` = Xyes ]
 	then
 		# this is here temporarily, for testing purposes
-		/bin/service -c up /sbin/ahci -dev /dev/c0d0 -label ahci_0 -args instance=0
+		/bin/service -c up /service/ahci -dev /dev/c0d0 -label ahci_0 -args instance=0
 	elif [ X"$virtio_blk" = Xyes ]
 	then
-		/bin/service -c up /sbin/virtio_blk -dev /dev/c0d0 -label virtio_blk_0 -args instance=0
+		/bin/service -c up /service/virtio_blk -dev /dev/c0d0 -label virtio_blk_0 -args instance=0
 	else
-		/bin/service -c up /sbin/at_wini -dev /dev/c0d0 -label at_wini_0
-		/bin/service -cr up /sbin/at_wini -dev /dev/c1d0 -label at_wini_1 -args instance=1 2>/dev/null || :
+		/bin/service -c up /service/at_wini -dev /dev/c0d0 -label at_wini_0
+		/bin/service -cr up /service/at_wini -dev /dev/c1d0 -label at_wini_1 -args instance=1 2>/dev/null || :
 	fi
 	/bin/umount /proc >/dev/null
 fi
 
 if [ X`/bin/sysenv arch` = Xearm ]
 then	echo Starting the mmc driver
-	/bin/service -c up /sbin/mmc -dev /dev/c0d0
+	/bin/service -c up /service/mmc -dev /dev/c0d0
 fi
 
-/bin/service up /sbin/procfs || echo "WARNING: couldn't start procfs"
+/bin/service up /service/procfs || echo "WARNING: couldn't start procfs"
 
 if /bin/sysenv rootdevname >/dev/null
 then	rootdevname=/dev/`/bin/sysenv rootdevname`
