Rename MINIX service(8) to minix-service(8)
IMPORTANT: this change has a docs/UPDATING entry!

This rename is unfortunately necessary because NetBSD has decided to
create its own service(8) utility, and we will want to import theirs
as well.  The two can obviously not coexist.

Also move ours from /bin to /sbin, as it is a superuser-only utility.

Change-Id: Ic6e46ffb3a84b4747d2fdcb0d74e62dbea065039

diff --git a/minix/drivers/storage/ramdisk/rc b/minix/drivers/storage/ramdisk/rc
--- a/minix/drivers/storage/ramdisk/rc
+++ b/minix/drivers/storage/ramdisk/rc
@@ -5,18 +5,20 @@ exec >/dev/log
 exec 2>/dev/log
 exec </dev/null
 
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
 FSCK=/bin/fsck_mfs
 ACPI=/service/acpi
 
 if [ X`/bin/sysenv arch` = Xi386 ]
 then	if [ -e $ACPI -a -n "`sysenv acpi`" ]
 	then
-		/bin/service -c up $ACPI
+		minix-service -c up $ACPI
 	fi
-	/bin/service -c up /service/pci -dev /dev/pci
+	minix-service -c up /service/pci -dev /dev/pci
 
-	/bin/service -c up /service/input -dev /dev/kbdmux
-	/bin/service -c up /service/pckbd || :
+	minix-service -c up /service/input -dev /dev/kbdmux
+	minix-service -c up /service/pckbd || :
 
 	# Start procfs so we can access /proc/pci
 	mount -t procfs none /proc >/dev/null
@@ -30,27 +32,27 @@ then	if [ -e $ACPI -a -n "`sysenv acpi`" ]
 		virtio_blk=yes
         fi
 
-	/bin/service -cn up /service/floppy -dev /dev/fd0
+	minix-service -cn up /service/floppy -dev /dev/fd0
 	if [ X`/bin/sysenv ahci` = Xyes ]
 	then
 		# this is here temporarily, for testing purposes
-		/bin/service -c up /service/ahci -dev /dev/c0d0 -label ahci_0 -args instance=0
+		minix-service -c up /service/ahci -dev /dev/c0d0 -label ahci_0 -args instance=0
 	elif [ X"$virtio_blk" = Xyes ]
 	then
-		/bin/service -c up /service/virtio_blk -dev /dev/c0d0 -label virtio_blk_0 -args instance=0
+		minix-service -c up /service/virtio_blk -dev /dev/c0d0 -label virtio_blk_0 -args instance=0
 	else
-		/bin/service -c up /service/at_wini -dev /dev/c0d0 -label at_wini_0
-		/bin/service -cr up /service/at_wini -dev /dev/c1d0 -label at_wini_1 -args instance=1 2>/dev/null || :
+		minix-service -c up /service/at_wini -dev /dev/c0d0 -label at_wini_0
+		minix-service -cr up /service/at_wini -dev /dev/c1d0 -label at_wini_1 -args instance=1 2>/dev/null || :
 	fi
 	/bin/umount /proc >/dev/null
 fi
 
 if [ X`/bin/sysenv arch` = Xearm ]
 then	echo Starting the mmc driver
-	/bin/service -c up /service/mmc -dev /dev/c0d0
+	minix-service -c up /service/mmc -dev /dev/c0d0
 fi
 
-/bin/service up /service/procfs || echo "WARNING: couldn't start procfs"
+minix-service up /service/procfs || echo "WARNING: couldn't start procfs"
 
 if /bin/sysenv rootdevname >/dev/null
 then	rootdevname=/dev/`/bin/sysenv rootdevname`
