run script:return 1 upon test failure.
Change-Id: If3c9d636a04da7f7b4098b58d29c492c664dab1a

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -59,6 +59,13 @@ for i in `echo $tests`; do
    fi
 done
 
+# 
+if [  $tests_no -eq 0 ]
+then
+	echo "No test binaries found. did you compile?"
+	exit 1
+fi
+
 if [ "$tests" = "$alltests" ]
 then	# Print test welcome message
 	clear
@@ -103,6 +110,12 @@ then	echo " "
 	             skipped $skipped
 	        echo The following tests failed: $badones
 	fi
+fi
+
+# if any test failed return an error
+if [ $failed -gt 0 ] 
+then
+	exit 1
 fi
 
 # echo " "
