crypto/external/bsd/heimdal - Update to Heimdal 7.1 Syncs with NetBSD-8

diff --git a/crypto/external/bsd/heimdal/dist/cf/Makefile.am.common b/crypto/external/bsd/heimdal/dist/cf/Makefile.am.common
--- a/crypto/external/bsd/heimdal/dist/cf/Makefile.am.common
+++ b/crypto/external/bsd/heimdal/dist/cf/Makefile.am.common
@@ -1,6 +1,6 @@
 # Id
 
-SUFFIXES = .et .h
+SUFFIXES = .et .h .pc.in .pc
 
 DEFAULT_INCLUDES = -I. -I$(srcdir) -I$(top_builddir)/include -I$(top_srcdir)/include
 
@@ -45,10 +45,8 @@ LIB_tgetent		= @LIB_tgetent@
 LIB_com_err		= @LIB_com_err@
 LIB_door_create		= @LIB_door_create@
 
-HESIODLIB = @HESIODLIB@
-HESIODINCLUDE = @HESIODINCLUDE@
-INCLUDE_hesiod = @INCLUDE_hesiod@
-LIB_hesiod = @LIB_hesiod@
+LIB_openssl_crypto      = @LIB_openssl_crypto@
+INCLUDE_openssl_crypto  = @INCLUDE_openssl_crypto@
 
 INCLUDE_krb4 = @INCLUDE_krb4@
 LIB_krb4 = @LIB_krb4@
@@ -66,17 +64,31 @@ libexec_heimdaldir = $(libexecdir)/heimdal
 install-suid-programs:
 	@foo='$(bin_SUIDS)'; \
 	for file in $$foo; do \
-	x=$(DESTDIR)$(bindir)/$$file; \
-	if chown 0:0 $$x && chmod u+s $$x; then :; else \
-	echo "*"; \
-	echo "* Failed to install $$x setuid root"; \
-	echo "*"; \
-	fi; done
+		x=$(DESTDIR)$(bindir)/$$file; \
+		if chown 0:0 $$x && chmod u+s $$x; then :; else \
+			echo "*"; \
+			echo "* Failed to install $$x setuid root"; \
+			echo "*"; \
+		fi; \
+	done
 
-install-exec-hook: install-suid-programs
+install-exec-local: install-suid-programs
 
-install-build-headers:: $(include_HEADERS) $(dist_include_HEADERS) $(nodist_include_HEADERS) $(build_HEADERZ) $(nobase_include_HEADERS)
-	@foo='$(include_HEADERS) $(dist_include_HEADERS) $(nodist_include_HEADERS) $(build_HEADERZ)'; \
+codesign-all:
+	@if [ X"$$CODE_SIGN_IDENTITY" != X ] ; then \
+		foo='$(bin_PROGRAMS) $(sbin_PROGRAMS) $(libexec_PROGRAMS)' ; \
+		for file in $$foo ; do \
+			echo "CODESIGN $$file" ; \
+			codesign -f -s "$$CODE_SIGN_IDENTITY" $$file || exit 1 ; \
+		done ; \
+	fi
+	
+
+
+all-local: codesign-all
+
+install-build-headers:: $(include_HEADERS) $(dist_include_HEADERS) $(nodist_include_HEADERS) $(build_HEADERZ) $(nobase_include_HEADERS) $(noinst_HEADERS)
+	@foo='$(include_HEADERS) $(dist_include_HEADERS) $(nodist_include_HEADERS) $(build_HEADERZ) $(noinst_HEADERS)'; \
 	for f in $$foo; do \
 		f=`basename $$f`; \
 		if test -f "$(srcdir)/$$f"; then file="$(srcdir)/$$f"; \
@@ -84,7 +96,7 @@ install-build-headers:: $(include_HEADERS) $(dist_include_HEADERS) $(nodist_incl
 		if cmp -s  $$file $(buildinclude)/$$f 2> /dev/null ; then \
 		: ; else \
 			echo " $(CP) $$file $(buildinclude)/$$f"; \
-			$(CP) $$file $(buildinclude)/$$f; \
+			$(CP) $$file $(buildinclude)/$$f || true; \
 		fi ; \
 	done ; \
 	foo='$(nobase_include_HEADERS)'; \
@@ -137,7 +149,7 @@ SUFFIXES += .x .z .hx
 .hx.h:
 	@cmp -s $< $@ 2> /dev/null || cp $< $@
 
-SUFFIXES += .1 .3 .5 .8 .cat1 .cat3 .cat5 .cat8
+SUFFIXES += .1 .3 .5 .7 .8 .cat1 .cat3 .cat5 .cat7 .cat8
 
 NROFF_MAN = groff -mandoc -Tascii
 #NROFF_MAN = nroff -man
@@ -146,6 +158,8 @@ NROFF_MAN = groff -mandoc -Tascii
 .3.cat3:
 	$(NROFF_MAN) $< > $@
 .5.cat5:
+	$(NROFF_MAN) $< > $@
+.7.cat7:
 	$(NROFF_MAN) $< > $@
 .8.cat8:
 	$(NROFF_MAN) $< > $@
@@ -191,6 +205,19 @@ dist-cat5-mans:
 		$(NROFF_MAN) $(srcdir)/$$i > $(distdir)/$$x; \
 	done
 
+dist-cat7-mans:
+	@foo='$(man7_MANS)'; \
+	bar='$(man_MANS)'; \
+	for i in $$bar; do \
+	case $$i in \
+	*.7) foo="$$foo $$i";; \
+	esac; done ;\
+	for i in $$foo; do \
+		x=`echo $$i | sed 's/\.[^.]*$$/.cat7/'`; \
+		echo "$(NROFF_MAN) $(srcdir)/$$i > $(distdir)/$$x"; \
+		$(NROFF_MAN) $(srcdir)/$$i > $(distdir)/$$x; \
+	done
+
 dist-cat8-mans:
 	@foo='$(man8_MANS)'; \
 	bar='$(man_MANS)'; \
@@ -204,13 +231,13 @@ dist-cat8-mans:
 		$(NROFF_MAN) $(srcdir)/$$i > $(distdir)/$$x; \
 	done
 
-dist-hook: dist-cat1-mans dist-cat3-mans dist-cat5-mans dist-cat8-mans
+dist-hook: dist-cat1-mans dist-cat3-mans dist-cat5-mans dist-cat7-mans dist-cat8-mans
 
 install-cat-mans:
-	$(SHELL) $(top_srcdir)/cf/install-catman.sh install "$(INSTALL_DATA)" "$(mkinstalldirs)" "$(srcdir)" "$(DESTDIR)$(mandir)" '$(CATMANEXT)' $(man_MANS) $(man1_MANS) $(man3_MANS) $(man5_MANS) $(man8_MANS)
+	$(SHELL) $(top_srcdir)/cf/install-catman.sh install "$(INSTALL_DATA)" "$(mkinstalldirs)" "$(srcdir)" "$(DESTDIR)$(mandir)" '$(CATMANEXT)' $(man_MANS) $(man1_MANS) $(man3_MANS) $(man5_MANS) $(man7_MANS) $(man8_MANS)
 
 uninstall-cat-mans:
-	$(SHELL) $(top_srcdir)/cf/install-catman.sh uninstall "$(INSTALL_DATA)" "$(mkinstalldirs)" "$(srcdir)" "$(DESTDIR)$(mandir)" '$(CATMANEXT)' $(man_MANS) $(man1_MANS) $(man3_MANS) $(man5_MANS) $(man8_MANS)
+	$(SHELL) $(top_srcdir)/cf/install-catman.sh uninstall "$(INSTALL_DATA)" "$(mkinstalldirs)" "$(srcdir)" "$(DESTDIR)$(mandir)" '$(CATMANEXT)' $(man_MANS) $(man1_MANS) $(man3_MANS) $(man5_MANS) $(man7_MANS) $(man8_MANS)
 
 install-data-hook: install-cat-mans
 uninstall-hook: uninstall-cat-mans
@@ -221,7 +248,11 @@ uninstall-hook: uninstall-cat-mans
 .et.c:
 	$(COMPILE_ET) $<
 
+if NO_AFS
+LIB_kafs =
+else
 LIB_kafs = $(top_builddir)/lib/kafs/libkafs.la $(AIX_EXTRA_KAFS)
+endif
 
 if KRB5
 LIB_krb5 = $(top_builddir)/lib/krb5/libkrb5.la \
@@ -229,7 +260,7 @@ LIB_krb5 = $(top_builddir)/lib/krb5/libkrb5.la \
 LIB_gssapi = $(top_builddir)/lib/gssapi/libgssapi.la
 endif
 
-LIB_heimbase = $(top_builddir)/base/libheimbase.la
+LIB_heimbase = $(top_builddir)/lib/base/libheimbase.la
 
 if DCE
 LIB_kdfs = $(top_builddir)/lib/kdfs/libkdfs.la
@@ -255,3 +286,10 @@ distdir-in-tree: $(DISTFILES) $(INFO_DEPS)
 	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) distdir-in-tree) ; \
 	  fi ; \
 	done
+
+
+#silent-rules
+
+heim_verbose = $(heim_verbose_$(V))
+heim_verbose_ = $(heim_verbose_$(AM_DEFAULT_VERBOSITY))
+heim_verbose_0 = @echo "  GEN    "$@;
diff --git a/crypto/external/bsd/heimdal/dist/tests/gss/check-context.in b/crypto/external/bsd/heimdal/dist/tests/gss/check-context.in
--- a/crypto/external/bsd/heimdal/dist/tests/gss/check-context.in
+++ b/crypto/external/bsd/heimdal/dist/tests/gss/check-context.in
@@ -34,8 +34,11 @@
 # Id
 #
 
+env_setup="@env_setup@"
 srcdir="@srcdir@"
 objdir="@objdir@"
+
+. ${env_setup}
 
 # If there is no useful db support compile in, disable test
 ../db/have-db || exit 77
@@ -50,6 +53,7 @@ nokeytab="FILE:no-such-keytab"
 cache="FILE:krb5ccfile"
 
 kinit="${TESTS_ENVIRONMENT} ../../kuser/kinit -c $cache ${afs_no_afslog}"
+klist="${TESTS_ENVIRONMENT} ../../kuser/heimtools klist -c $cache"
 klist="${TESTS_ENVIRONMENT} ../../kuser/klist -c $cache"
 kgetcred="${TESTS_ENVIRONMENT} ../../kuser/kgetcred -c $cache"
 kadmin="${TESTS_ENVIRONMENT} ../../kadmin/kadmin -l -r $R"
@@ -81,8 +85,6 @@ ${kadmin} \
 # add both lucid and lucid.test.h5l.se to simulate aliases
 ${kadmin} add -p p1 --use-defaults host/lucid.test.h5l.se@${R} || exit 1
 ${kadmin} ext -k ${keytab} host/lucid.test.h5l.se@${R} || exit 1
-${kadmin} add -p p1 --use-defaults host/lucid@${R} || exit 1
-${kadmin} ext -k ${keytab} host/lucid@${R} || exit 1
 
 ${kadmin} add -p p1 --use-defaults host/ok-delegate.test.h5l.se@${R} || exit 1
 ${kadmin} mod --attributes=+ok-as-delegate host/ok-delegate.test.h5l.se@${R} || exit 1
@@ -112,18 +114,30 @@ ${kadmin} check ${R} || exit 1
 echo u1 > ${objdir}/foopassword
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
 testfailed="echo test failed; cat messages.log; exit 1"
+
+echo "Test gss_acquire_cred_with_password" ; > messages.log
+${context} --client-name=user1@${R} --client-password=u1 --mech-type=krb5 \
+        host@lucid.test.h5l.se || { eval "$testfailed"; }
+# These must fail (because wrong password)
+${context} --client-name=user1@${R} --client-password=u2 --mech-type=krb5 \
+        host@lucid.test.h5l.se && { eval "$testfailed"; }
+${context} --client-name=user1@${R} --client-password=u2 --mech-type='' \
+        --mech-types=krb5 host@lucid.test.h5l.se && { eval "$testfailed"; }
+${context} --client-name=user1@${R} --client-password=u2 --mech-type=krb5 \
+        --mech-types=krb5 host@lucid.test.h5l.se && { eval "$testfailed"; }
+${context} --client-name=user1@${R} --client-password=u2 --mech-type=all \
+        --mech-types=krb5 host@lucid.test.h5l.se && { eval "$testfailed"; }
+${context} --client-name=user1@${R} --client-password=u2 \
+        --mech-type=krb5,ntlm --mech-types=krb5 host@lucid.test.h5l.se \
+        && { eval "$testfailed"; }
+# gss_acquire_cred_with_password() must not have side-effects
+${klist} && { eval "$testfailed"; }
 
 echo "Getting client initial tickets" ; > messages.log
 ${kinit} --password-file=${objdir}/foopassword --forwardable user1@${R} || \
@@ -152,12 +166,21 @@ echo "======test naming combinations"
 echo "plain"  ; > messages.log
 ${context} --name-type=hostbased-service host@lucid.test.h5l.se || \
 	{ eval "$testfailed"; }
+echo "plain w/ short-form hostname"  ; > messages.log
+${context} --name-type=hostbased-service host@lucid || \
+	{ eval "$testfailed"; }
 echo "plain (krb5)" ; > messages.log
 ${context} --name-type=krb5-principal-name host/lucid.test.h5l.se@${R} || \
 	{ eval "$testfailed"; }
 echo "plain (krb5 realmless)" ; > messages.log
 ${context} --name-type=krb5-principal-name host/lucid.test.h5l.se || \
 	{ eval "$testfailed"; }
+echo "plain (krb5 realmless short-form)" ; > messages.log
+${context} --name-type=krb5-principal-name host/lucid 2>/dev/null || \
+	{ eval "$testfailed"; }
+echo "creating short-form princ"
+${kadmin} add -p p1 --use-defaults host/lucid@${R} || exit 1
+${kadmin} ext -k ${keytab} host/lucid@${R} || exit 1
 echo "dns canon on (long name) OFF, need dns_wrapper" ; > messages.log
 #${context} --dns-canon host@lucid.test.h5l.se || \
 #	{ eval "$testfailed"; }
diff --git a/crypto/external/bsd/heimdal/dist/tests/gss/check-gssmask.in b/crypto/external/bsd/heimdal/dist/tests/gss/check-gssmask.in
--- a/crypto/external/bsd/heimdal/dist/tests/gss/check-gssmask.in
+++ b/crypto/external/bsd/heimdal/dist/tests/gss/check-gssmask.in
@@ -34,8 +34,11 @@
 # Id
 #
 
+env_setup="@env_setup@"
 srcdir="@srcdir@"
 objdir="@objdir@"
+
+. ${env_setup}
 
 # If there is no useful db support compile in, disable test
 ../db/have-db || exit 77
@@ -85,14 +88,8 @@ echo "Doing database check"
 ${kadmin} check ${R} || exit 1
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
diff --git a/crypto/external/bsd/heimdal/dist/tests/java/check-kinit.in b/crypto/external/bsd/heimdal/dist/tests/java/check-kinit.in
--- a/crypto/external/bsd/heimdal/dist/tests/java/check-kinit.in
+++ b/crypto/external/bsd/heimdal/dist/tests/java/check-kinit.in
@@ -35,8 +35,11 @@
 #
 
 srcdir="@srcdir@"
+env_setup="@env_setup@"
 objdir="@objdir@"
 port="@port@"
+
+. ${env_setup}
 
 # Disable test if: no data, no java, or socket wrapper
 ../db/have-db || exit 77
@@ -44,9 +47,15 @@ sh ${srcdir}/have-java.sh || exit 77
 [ X"$SOCKET_WRAPPER_DIR" != X ] && exit 77
 
 R=TEST.H5L.SE
+server=host/localhost
+keytabfile="${objdir}/server.keytab"
+keytab="FILE:${keytabfile}"
+cache="FILE:${objdir}/cache.krb5"
 
+kinit="${TESTS_ENVIRONMENT} ../../kuser/kinit -c $cache ${afs_no_afslog}"
 kadmin="${TESTS_ENVIRONMENT} ../../kadmin/kadmin -l -r $R"
 kdc="${TESTS_ENVIRONMENT} ../../kdc/kdc --addresses=127.0.0.1 -P $port"
+gssclient="${TESTS_ENVIRONMENT} ../../appl/test/gssapi_client"
 
 KRB5_CONFIG="${objdir}/krb5.conf"
 export KRB5_CONFIG
@@ -60,7 +69,13 @@ echo "Compile"
 javac -d "${objdir}" "${srcdir}/KerberosInit.java" || \
     { echo "Failed to compile java program: $?" ; exit 77; }
 
+echo "Compile"
+javac -d "${objdir}" "${srcdir}/../../appl/test/jgssapi_server.java" || \
+    { echo "Failed to compile java program: $?" ; exit 77; }
+
 > messages.log
+
+echo foo > ${objdir}/foopassword
 
 echo Creating database
 ${kadmin} \
@@ -71,30 +86,61 @@ ${kadmin} \
 
 ${kadmin} add -p foo --use-defaults lha@${R} || exit 1
 ${kadmin} modify --attributes=+requires-pre-auth lha@${R} || exit 1
+${kadmin} add -p kaka --use-defaults ${server}@${R} || exit 1
+${kadmin} ext -k ${keytab} ${server}@${R} || exit 1
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
-
-trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
+trap "kill -9 ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
 echo "Run init"
 java \
-  -Dsun.security.krb5.debug=true \
-  -Djava.security.krb5.conf="${objdir}"/krb5.conf \
-  -Djava.security.auth.login.config="${srcdir}/jaas.conf" \
-  KerberosInit > output.tmp 2>&1 || { cat output.tmp ; exit 1; }
+    -Dsun.security.krb5.debug=true \
+    -Djava.security.krb5.conf="${objdir}"/krb5.conf \
+    -Djava.security.auth.login.config="${srcdir}/jaas.conf" \
+    KerberosInit > output.tmp 2>&1 || { cat output.tmp ; exit 1; }
+
+
+# Disabled because of:
+#
+# http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7077646
+# http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7077640
+#
+
+if false ; then
+
+    echo "start server"
+    java \
+        -Dsun.security.krb5.debug=true \
+        -Djava.security.krb5.conf="${objdir}"/krb5.conf \
+        -Djavax.security.auth.useSubjectCredsOnly=false \
+        -Djava.security.auth.login.config="${srcdir}/jaas.conf" \
+        jgssapi_server > output.tmp 2>&1 &
+    javapid=$!
+    sleep 5
+    
+    trap "kill -9 ${kdcpid} ${javapid}; echo signal killing kdc java; exit 1;" EXIT
+    
+    echo "Getting client initial tickets"; > messages.log
+    ${kinit} --password-file=${objdir}/foopassword lha@$R || \
+    	{ echo "kinit failed" ; exit 1; }
+    
+    env KRB5CCNAME=${cache} \
+        ${gssclient} --port=4717 --service=host localhost || exit 1
+    
+    sleep 5
+    
+    kill ${javapid}
+    
+    grep 'Exception in thread' output.tmp && exit 1
+fi
 
 echo "Done"
 
-echo "killing kdc (${kdcpid})"
-kill $kdcpid || exit 1
+echo "killing kdc (${kdcpid} ${javapid})"
+kill $kdcpid $javapid || exit 1
 
 trap "" EXIT
 
diff --git a/crypto/external/bsd/heimdal/dist/tests/kdc/check-kpasswdd.in b/crypto/external/bsd/heimdal/dist/tests/kdc/check-kpasswdd.in
--- a/crypto/external/bsd/heimdal/dist/tests/kdc/check-kpasswdd.in
+++ b/crypto/external/bsd/heimdal/dist/tests/kdc/check-kpasswdd.in
@@ -101,19 +101,15 @@ ${kadmin} check ${R2} || exit 1
 
 echo foo > ${objdir}/foopassword
 
-echo Starting kdc
-env ${HEIM_MALLOC_DEBUG} ${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+echo Starting kdc ; > messages.log
+env ${HEIM_MALLOC_DEBUG} ${kdc} --detach --testing ||
+    { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 echo Starting kpasswdd
-env ${HEIM_MALLOC_DEBUG} ${kpasswdd} &
-kpasswddpid=$!
+env ${HEIM_MALLOC_DEBUG} ${kpasswdd} --detach ||
+    { echo "kpasswdd failed to start"; exit 1; }
+kpasswddpid=`getpid kpasswdd`
 
 trap "kill -9 ${kdcpid} ${kpasswddpid}; echo signal killing kdc; exit \$ec;" EXIT
 
diff --git a/crypto/external/bsd/heimdal/dist/tests/kdc/check-pkinit.in b/crypto/external/bsd/heimdal/dist/tests/kdc/check-pkinit.in
--- a/crypto/external/bsd/heimdal/dist/tests/kdc/check-pkinit.in
+++ b/crypto/external/bsd/heimdal/dist/tests/kdc/check-pkinit.in
@@ -168,15 +168,9 @@ ${hxtool} issue-certificate \
 
 echo foo > ${objdir}/foopassword
 
-echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+echo Starting kdc ; > messages.log
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid}; echo signal killing kdc; cat ca.crt kdc.crt pkinit.crt ;exit 1;" EXIT
 
diff --git a/crypto/external/bsd/heimdal/dist/tests/kdc/check-uu.in b/crypto/external/bsd/heimdal/dist/tests/kdc/check-uu.in
--- a/crypto/external/bsd/heimdal/dist/tests/kdc/check-uu.in
+++ b/crypto/external/bsd/heimdal/dist/tests/kdc/check-uu.in
@@ -61,7 +61,6 @@ kdestroy2="${TESTS_ENVIRONMENT} ../../kuser/kdestroy -c $cache2 ${afs_no_unlog}"
 uu_server="${TESTS_ENVIRONMENT} ../../appl/test/uu_server"
 uu_client="${TESTS_ENVIRONMENT} ../../appl/test/uu_client"
 
-
 KRB5_CONFIG="${objdir}/krb5.conf"
 export KRB5_CONFIG
 
@@ -86,15 +85,9 @@ ${kadmin} check ${R} || exit 1
 
 echo foo > ${objdir}/foopassword
 
-echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+echo Starting kdc ; > messages.log
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid} ${uuspid}; echo signal killing kdc; exit 1;" EXIT
 
