Added a hack to start binaries from the boot image only. In particular, setting bin_img=1 in the boot monitor will make sure that during the boot procedure the mfs binary that is part of the boot image is the only binary that is used to mount partitions. This is useful when for some reason the mfs binary on disk malfunctions, rendering Minix unable to boot. By setting bin_img=1, the binary on disk is ignored and the binary in the boot image is used instead.
- 'service' now accepts an additional flag -r. -r implies -c. -r instructs RS
  to first look in memory if the binary has already been copied to memory and
  execute that version, instead of loading the binary from disk. For example,
  the first time a MFS is being started it is copied (-c) to memory and
  executed from there. The second time MFS is being started this way, RS will
  look in memory for a previously copied MFS binary and reuse it if it exists.
- The mount and newroot commands now accept an additional flag -i, which
  instructs them to set the MS_REUSE flag in the mount flags.
- The mount system call now supports the MS_REUSE flag and invokes 'service'
  with the -r flag when MS_REUSE is set.
- /etc/rc and the rc script that's included in the boot image check for the
  existence of the bin_img flag in the boot monitor, and invoke mount and 
  newroot with the -i flag accordingly.

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -73,6 +73,12 @@ start)
     # Any swapspace on a device?
     test "$swap" : '/dev/' && mount -s $swap
 
+    # Use MFS binary only from kernel image?
+    if [ "`sysenv bin_img`" = 1 ]
+    then
+        bin_img="-i "
+    fi
+
     # Are we booting from CD?
     bootcd="`/bin/sysenv bootcd`"
 
@@ -89,6 +95,7 @@ start)
     		echo "Setting /usr on cd is $usr"
     fi
  
+
     # Mount the /usr partition unless this is a single floppy Minix.
     if [ ! -d /usr/bin ]
     then
@@ -101,7 +108,8 @@ start)
 		echo "usr=/dev/$usr" >/tmp/usr'
 	    . /tmp/usr
 	fi
-	mount $usr_roflag $usr /usr || {
+
+	mount $bin_img $usr_roflag $usr /usr || {
 	    echo "\
 Please try to mount something else as /usr, then hit CTRL-D to continue startup.
 Mount $usr /usr failed -- Single user."
@@ -129,11 +137,11 @@ Mount $usr /usr failed -- Single user."
 	then	echo "fsck /home - $home"
 		intr fsck -r $home
 	fi
-	mount $usr /usr
+	mount $bin_img $usr /usr
     fi
 
     if [ ! -z "$home" ]
-    then mount $home /home || echo "WARNING: couldn't mount $home on /home"
+    then mount $bin_img $home /home || echo "WARNING: couldn't mount $home on /home"
     fi
 
     # This file is necessary for above 'shutdown -C' check.
