VM: full munmap
complete munmap implementation; single-page references made
a general munmap() implementation possible to write cleanly.

	. memory: let the MIOCRAMSIZE ioctl set the imgrd device
	  size (but only to 0)
	. let the ramdisk command set sizes to 0
	. use this command to set /dev/imgrd to 0 after mounting /usr
	  in /etc/rc, so the boot time ramdisk is freed (about 4MB
	  currently)

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -121,9 +121,6 @@ start)
     printroot >/etc/mtab		# /etc/mtab keeps track of mounts
     >/etc/utmp				# /etc/utmp keeps track of logins
 
-    # Unmount now defunct ramdisk
-    umount /dev/imgrd > /dev/null || echo "Failed to unmount boot ramdisk"
-
     # Use MFS binary only from kernel image?
     if [ "`sysenv bin_img`" = 1 ]
     then
@@ -148,6 +145,10 @@ start)
 			mount -a
 		fi
     fi
+
+    # Unmount and free now defunct ramdisk
+    umount /dev/imgrd > /dev/null || echo "Failed to unmount boot ramdisk"
+    ramdisk 0 /dev/imgrd || echo "Failed to free boot ramdisk"
 
     # Edit settings for boot system services
     if [ "`sysenv skip_boot_config`" != 1 ]
