/home fixes

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -135,7 +135,10 @@ Mount $usr /usr failed -- Single user."
 	then	intr fsck -r $home
 	fi
 	mount $usr /usr
-	mount $home /home
+    fi
+
+    if [ ! -z "$home" ]
+    then mount $home /home || echo 'WARNING: couldn't mount $home on /home"
     fi
 
     # This file is necessary for above 'shutdown -C' check.
