mainstream-format fstab format
	. detect both formats in /etc/rc
	. generate new format in setup
	. obsoletes /etc/fstab.local: everything can go in /etc/fstab
	. put shutdown/reboot/halt and a copy of /usr/adm/wtmp
	  (/etc/wtmp) on root FS so that we can do shutdown checks before
	  mounting /usr
	. new fstab format makes getfsent() and friends work

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,10 +1,13 @@
 # /etc/rc - System startup script run by init before going multiuser.
 
+. /etc/rc.subr.minix
+
 exec >/dev/log
 exec 2>/dev/log
 exec </dev/null
 
 umask 022
+FSTAB=/etc/fstab
 TERM="${TERM-minix}"
 PATH=/usr/local/bin:/bin:/usr/bin:/usr/sbin:/usr/pkg/bin:/usr/pkg/sbin:/sbin
 RC_TZ=/etc/rc.timezone
@@ -46,7 +49,42 @@ edit()
     shift
 
     # Assume binaries are always in /usr/sbin
-    service $opt edit /usr/sbin/$service -label $service "$@"
+    service $opt edit /usr/sbin/$service -label $service "$@" 
+}
+
+# This function parses the deprecated minix shellscript-style 
+# /etc/fstab, and fscks and mounts its filesystems.
+mountfstab_poorman()
+{
+    # /etc/fstab lists the root, tmp and usr devices.
+    . $FSTAB
+
+    # Check if the system crashed.
+    if shutdown -C
+    then
+	echo
+	echo "The system was not properly shut down.  Checking file systems."
+	fflag=-f
+    fi
+
+    if [ -n "$fflag" ]
+    then
+	echo "fsck.mfs / - $root"
+	intr fsck.mfs $fsckopts $root
+	echo "fsck.mfs /usr - $usr"
+	intr fsck.mfs $fsckopts $usr
+	if [ ! -z "$home" ]
+	then	echo "fsck.mfs /home - $home"
+		intr fsck.mfs $fsckopts $home
+	fi
+    fi
+
+    # mount /usr
+    mount $bin_img $usr /usr
+
+    if [ ! -z "$home" ]
+    then mount $bin_img $home /home || echo "WARNING: couldn't mount $home on /home"
+    fi
 }
 
 while getopts 'saf' opt
@@ -54,7 +92,7 @@ do
     case $opt in
     s)	sflag=t ;;	# Single user
     a)	aflag=t ;;	# Ask for /usr
-    f)	fflag=t ;;	# Force a full file system check
+    f)	fflag=-f ;;	# Force a full file system check
     *)	usage
     esac
 done
@@ -99,9 +137,6 @@ start)
     printroot >/etc/mtab		# /etc/mtab keeps track of mounts
     >/etc/utmp				# /etc/utmp keeps track of logins
 
-    # /etc/fstab lists the root, tmp and usr devices.
-    . /etc/fstab
-
     # Unmount now defunct ramdisk
     umount /dev/imgrd > /dev/null || echo "Failed to unmount boot ramdisk"
 
@@ -114,62 +149,19 @@ start)
     # Are we booting from CD?
     bootcd="`/bin/sysenv bootcd`"
 
-    # If booting from CD, /usr has to be mounted readonly.
-    # Also, $usr won't be specified correctly in the
-    # fstab (the CD could be anywhere), so we decide
-    # where it is based on sysenv (set by FS when probing for CD).
+    # If booting from CD, mounting is a special case.
+    # We know what to do - only /usr is mounted and it's readonly.
     if [ "$bootcd" = 1 ]
-    then	
-    		#imagedev="`/bin/sysenv cdproberoot`"
-    		#usrdev="`expr $imagedev + 1`"
-    		usr_roflag="-r"
-    		usr="$cddev"p2
-    		echo "Setting /usr on cd is $usr"
-    fi
- 
-
-    # Mount the /usr partition unless this is a single floppy Minix.
-    if [ ! -d /usr/bin ]
-    then
-	if [ "$aflag" -o "$usr" = unknown ]
-	then
-	    # We need to ask what the /usr du jour is.
-	    intr sh -c '
-		echo -n "Finish the name of device to mount as /usr: /dev/"
-		read usr
-		echo "usr=/dev/$usr" >/tmp/usr'
-	    . /tmp/usr
-	fi
-
-	mount $bin_img $usr_roflag $usr /usr || {
-	    echo "\
-Please try to mount something else as /usr, then hit CTRL-D to continue startup.
-Mount $usr /usr failed -- Single user."
-	    intr sh
-	}
-	rm -f /tmp/usr
-    fi
-
-    # Check if the system crashed.
-    if shutdown -C
-    then
-	echo
-	echo "The system was not properly shut down.  Checking file systems."
-	fflag=t
-    fi
-
-    if [ "$fflag" ]
-    then
-	umount $usr
-	echo "fsck.mfs / - $root"
-	intr fsck.mfs $fsckopts $root
-	echo "fsck.mfs /usr - $usr"
-	intr fsck.mfs $fsckopts $usr
-	if [ ! -z "$home" ]
-	then	echo "fsck.mfs /home - $home"
-		intr fsck.mfs $fsckopts $home
-	fi
-	mount $bin_img $usr /usr
+    then	usrdev="$cddev"p2
+    		echo "/usr on cd is $usrdev"
+		mount -r $usrdev /usr
+    else	
+    # If we're not booting from CD, fsck + mount using /etc/fstab.
+		read <$FSTAB fstabline
+		if [ "$fstabline" = "# Poor man's File System Table." ]
+		then	mountfstab_poorman	# Old minix /etc/fstab
+		else	mountfstab $fflag -o"$fsckopts" $FSTAB	
+		fi
     fi
 
     # Edit settings for boot system services
@@ -188,13 +180,9 @@ Mount $usr /usr failed -- Single user."
 	edit init
     fi
 
-    if [ ! -z "$home" ]
-    then mount $bin_img $home /home || echo "WARNING: couldn't mount $home on /home"
-    fi
-
     # This file is necessary for above 'shutdown -C' check.
     # (Silence stderr in case of running from cd.)
-    touch /usr/adm/wtmp 2>/dev/null
+    touch /usr/adm/wtmp /etc/wtmp 2>/dev/null
 
     if [ "$sflag" ]
     then
