NetBSD re-synchronization of the source tree
This brings our tree to NetBSD 7.0, as found on -current on the
10-10-2015.

This updates:
 - LLVM to 3.6.1
 - GCC to GCC 5.1
 - Replace minix/commands/zdump with usr.bin/zdump
 - external/bsd/libelf has moved to /external/bsd/elftoolchain/
 - Import ctwm
 - Drop sprintf from libminc

Change-Id: I149836ac18e9326be9353958bab9b266efb056f0

diff --git a/crypto/external/bsd/heimdal/dist/tests/kdc/check-digest.in b/crypto/external/bsd/heimdal/dist/tests/kdc/check-digest.in
--- a/crypto/external/bsd/heimdal/dist/tests/kdc/check-digest.in
+++ b/crypto/external/bsd/heimdal/dist/tests/kdc/check-digest.in
@@ -131,20 +131,19 @@ export NTLM_USER_FILE
 
 echo "test_context --mech-type=ntlm"
 ${test_context} --mech-type=ntlm \
-	    --name-type=hostbased-service datan@TEST || \
-		{ echo "test_context 1 failed"; exit 1; }
+    --client-name=foo@TEST \
+    --name-type=hostbased-service datan@TEST || \
+    { echo "test_context 1 failed"; exit 1; }
 
 ${test_context} --mech-type=ntlm \
-	    --name-type=hostbased-service datan@host.TEST || \
-		{ echo "test_context 2 failed"; exit 1; }
+    --client-name=foo@TEST \
+    --name-type=hostbased-service datan@host.TEST || \
+    { echo "test_context 2 failed"; exit 1; }
 
 ${test_context} --mech-type=ntlm \
-	    --name-type=hostbased-service datan@host.test.domain2 || \
-		{ echo "test_context 3 failed"; exit 1; }
-
-${test_context} --mech-type=ntlm \
-	    --name-type=hostbased-service datan@host.foo 2>/dev/null && \
-		{ echo "test_context 4 failed"; exit 1; }
+    --client-name=foo@TEST \
+    --name-type=hostbased-service datan@host.test.domain2 || \
+    { echo "test_context 3 failed"; exit 1; }
 
 echo "Trying SL in NTLM"
 
@@ -158,6 +157,7 @@ for type in \
 
 	echo "Trying NTLM type: ${type}"
 	${test_context} --mech-type=ntlm ${type} \
+	    --client-name=foo@TEST \
 	    --name-type=hostbased-service datan@TEST || \
 	    { echo "test_context 1 failed"; exit 1; }
 
