Changes to make gcc compile our libraries too (Joren)

diff --git a/lib/zlib-1.2.3/Makefile b/lib/zlib-1.2.3/Makefile
--- a/lib/zlib-1.2.3/Makefile
+++ b/lib/zlib-1.2.3/Makefile
@@ -1,5 +1,5 @@
 # Makefile for zlib
-# Copyright (C) 1995-2005 Jean-loup Gailly.
+# Copyright (C) 1995-2003 Jean-loup Gailly.
 # For conditions of distribution and use, see copyright notice in zlib.h
 
 # To compile and test, type:
@@ -16,139 +16,155 @@
 # To install in $HOME instead of /usr/local, use:
 #    make install prefix=$HOME
 
-CC=cc
+#CC=cc
 
-CFLAGS=-O -DNO_snprintf -DHAS_sprintf_void -DNO_ERRNO_H
+CFLAGS=-D_MINIX=1 -D_POSIX_SOURCE=1
 #CFLAGS=-O -DMAX_WBITS=14 -DMAX_MEM_LEVEL=7
 #CFLAGS=-g -DDEBUG
 #CFLAGS=-O3 -Wall -Wwrite-strings -Wpointer-arith -Wconversion \
 #           -Wstrict-prototypes -Wmissing-prototypes
 
-LDFLAGS=-L. libz.a
-LDSHARED=cc
-CPP=cc -E
+#LDFLAGS=-L. libz.a
+#LDSHARED=cc
+#CPP=cc -E
 
-LIBS=libz.a
-SHAREDLIB=libz.so
-SHAREDLIBV=libz.so.1.2.3
-SHAREDLIBM=libz.so.1
+#LIBS=libz.a
+LIBRARIES=libz
+#SHAREDLIB=libz.so
+#SHAREDLIBV=libz.so.1.2.2
+#SHAREDLIBM=libz.so.1
 
-AR=ar rc
-RANLIB=ranlib
-TAR=tar
-SHELL=/bin/sh
-EXE=
+#AR=ar rc
+#RANLIB=ranlib
+#TAR=tar
+#SHELL=/bin/sh
+#EXE=
 
-prefix =/usr/local
-exec_prefix =${prefix}
-libdir =${exec_prefix}/lib
-includedir =${prefix}/include
-mandir =${prefix}/share/man
-man3dir = ${mandir}/man3
+#prefix =/usr/local
+#exec_prefix =${prefix}
+#libdir =${exec_prefix}/lib
+#includedir =${prefix}/include
+#mandir =/usr/local/man
+#man3dir = ${mandir}/man3
 
-OBJS = adler32.o compress.o crc32.o gzio.o uncompr.o deflate.o trees.o \
-       zutil.o inflate.o infback.o inftrees.o inffast.o
+#OBJS = adler32.o compress.o crc32.o gzio.o uncompr.o deflate.o trees.o \
+#       zutil.o inflate.o infback.o inftrees.o inffast.o
 
-OBJA =
+#OBJA =
 # to use the asm code: make OBJA=match.o
 
-TEST_OBJS = example.o minigzip.o
+libz_OBJECTS = adler32.o compress.o crc32.o gzio.o uncompr.o deflate.o trees.o \
+       zutil.o inflate.o infback.o inftrees.o inffast.o
 
-all: example$(EXE) minigzip$(EXE)
+# to use the asm code: add match.o to liz_OBJECTS
 
-check: test
-test: all
-	@LD_LIBRARY_PATH=.:$(LD_LIBRARY_PATH) ; export LD_LIBRARY_PATH; \
-	echo hello world | ./minigzip | ./minigzip -d || \
-	  echo '		*** minigzip test FAILED ***' ; \
-	if ./example; then \
-	  echo '		*** zlib test OK ***'; \
-	else \
-	  echo '		*** zlib test FAILED ***'; \
-	fi
+#TEST_OBJS = example.o minigzip.o
 
-libz.a: $(OBJS) $(OBJA)
-	$(AR) $@ $(OBJS) $(OBJA)
-	-@ ($(RANLIB) $@ || true) >/dev/null 2>&1
+#all:: example$(EXE) minigzip$(EXE)
 
-match.o: match.S
-	$(CPP) match.S > _match.s
-	$(CC) -c _match.s
-	mv _match.o match.o
-	rm -f _match.s
+#check: test
+#test: all
+#	@LD_LIBRARY_PATH=.:$(LD_LIBRARY_PATH) ; export LD_LIBRARY_PATH; \
+#	echo hello world | ./minigzip | ./minigzip -d || \
+#	  echo '		*** minigzip test FAILED ***' ; \
+#	if ./example; then \
+#	  echo '		*** zlib test OK ***'; \
+#	else \
+#	  echo '		*** zlib test FAILED ***'; \
+#	fi
 
-$(SHAREDLIBV): $(OBJS)
-	$(LDSHARED) -o $@ $(OBJS)
-	rm -f $(SHAREDLIB) $(SHAREDLIBM)
-	ln -s $@ $(SHAREDLIB)
-	ln -s $@ $(SHAREDLIBM)
+#libz.a: $(OBJS) $(OBJA)
+#	$(AR) $@ $(OBJS) $(OBJA)
+#	-@ ($(RANLIB) $@ || true) >/dev/null 2>&1
 
-example$(EXE): example.o $(LIBS)
-	$(CC) $(CFLAGS) -o $@ example.o $(LDFLAGS)
+#match.o: match.S
+#	$(CPP) match.S > _match.s
+#	$(CC) -c _match.s
+#	mv _match.o match.o
+#	rm -f _match.s
 
-minigzip$(EXE): minigzip.o $(LIBS)
-	$(CC) $(CFLAGS) -o $@ minigzip.o $(LDFLAGS)
+#$(SHAREDLIBV): $(OBJS)
+#	$(LDSHARED) -o $@ $(OBJS)
+#	rm -f $(SHAREDLIB) $(SHAREDLIBM)
+#	ln -s $@ $(SHAREDLIB)
+#	ln -s $@ $(SHAREDLIBM)
 
-install: $(LIBS)
-	-@if [ ! -d $(exec_prefix) ]; then mkdir -p $(exec_prefix); fi
-	-@if [ ! -d $(includedir)  ]; then mkdir -p $(includedir); fi
-	-@if [ ! -d $(libdir)      ]; then mkdir -p $(libdir); fi
-	-@if [ ! -d $(man3dir)     ]; then mkdir -p $(man3dir); fi
-	cp zlib.h zconf.h $(includedir)
-	chmod 644 $(includedir)/zlib.h $(includedir)/zconf.h
-	cp $(LIBS) $(libdir)
-	cd $(libdir); chmod 755 $(LIBS)
-	-@(cd $(libdir); $(RANLIB) libz.a || true) >/dev/null 2>&1
-	cd $(libdir); if test -f $(SHAREDLIBV); then \
-	  rm -f $(SHAREDLIB) $(SHAREDLIBM); \
-	  ln -s $(SHAREDLIBV) $(SHAREDLIB); \
-	  ln -s $(SHAREDLIBV) $(SHAREDLIBM); \
-	  (ldconfig || true)  >/dev/null 2>&1; \
-	fi
-	cp zlib.3 $(man3dir)
-	chmod 644 $(man3dir)/zlib.3
+#example$(EXE): example.o $(LIBS)
+#	$(CC) $(CFLAGS) -o $@ example.o $(LDFLAGS)
+
+#minigzip$(EXE): minigzip.o $(LIBS)
+#	$(CC) $(CFLAGS) -o $@ minigzip.o $(LDFLAGS)
+
+#install: $(LIBS)
+#	-@if [ ! -d $(exec_prefix) ]; then mkdir -p $(exec_prefix); fi
+#	-@if [ ! -d $(includedir)  ]; then mkdir -p $(includedir); fi
+#	-@if [ ! -d $(libdir)      ]; then mkdir -p $(libdir); fi
+#	-@if [ ! -d $(man3dir)     ]; then mkdir -p $(man3dir); fi
+#	install -o bin zlib.h zconf.h $(includedir)
+#	chmod 644 $(includedir)/zlib.h $(includedir)/zconf.h
+#	install -o bin $(LIBS) $(libdir)
+#	cd $(libdir); chmod 755 $(LIBS)
+#	-@(cd $(libdir); $(RANLIB) libz.a || true) >/dev/null 2>&1
+#	cd $(libdir); if test -f $(SHAREDLIBV); then \
+#	  rm -f $(SHAREDLIB) $(SHAREDLIBM); \
+#	  ln -s $(SHAREDLIBV) $(SHAREDLIB); \
+#	  ln -s $(SHAREDLIBV) $(SHAREDLIBM); \
+#	  (ldconfig || true)  >/dev/null 2>&1; \
+#	fi
+#	install -o bin zlib.3 $(man3dir)
+#	chmod 644 $(man3dir)/zlib.3
 # The ranlib in install is needed on NeXTSTEP which checks file times
 # ldconfig is for Linux
 
-uninstall:
-	cd $(includedir); \
-	cd $(libdir); rm -f libz.a; \
-	if test -f $(SHAREDLIBV); then \
-	  rm -f $(SHAREDLIBV) $(SHAREDLIB) $(SHAREDLIBM); \
-	fi
-	cd $(man3dir); rm -f zlib.3
+#uninstall:
+#	cd $(includedir); \
+#	cd $(libdir); rm -f libz.a; \
+#	if test -f $(SHAREDLIBV); then \
+#	  rm -f $(SHAREDLIBV) $(SHAREDLIB) $(SHAREDLIBM); \
+#	fi
+#	cd $(man3dir); rm -f zlib.3
 
 mostlyclean: clean
-clean:
+clean::
 	rm -f *.o *~ example$(EXE) minigzip$(EXE) \
 	   libz.* foo.gz so_locations \
 	   _match.s maketree contrib/infback9/*.o
 
-maintainer-clean: distclean
-distclean: clean
-	cp -p Makefile.in Makefile
-	cp -p zconf.in.h zconf.h
-	rm -f .DS_Store
+#maintainer-clean: distclean
+#distclean: clean
+#	cp -p Makefile.in Makefile
+#	cp -p zconf.in.h zconf.h
+#	rm -f .DS_Store
 
-tags:
-	etags *.[ch]
+#tags:
+#	etags *.[ch]
+#
+#depend:
+#	makedepend -- $(CFLAGS) -- *.[ch]
 
-depend:
-	makedepend -- $(CFLAGS) -- *.[ch]
+## DO NOT DELETE THIS LINE -- make depend depends on it.
 
-# DO NOT DELETE THIS LINE -- make depend depends on it.
+#adler32.o: zlib.h zconf.h
+#compress.o: zlib.h zconf.h
+#crc32.o: crc32.h zlib.h zconf.h
+#deflate.o: deflate.h zutil.h zlib.h zconf.h
+#example.o: zlib.h zconf.h
+#gzio.o: zutil.h zlib.h zconf.h
+#inffast.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
+#inflate.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
+#infback.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
+#inftrees.o: zutil.h zlib.h zconf.h inftrees.h
+#minigzip.o: zlib.h zconf.h
+#trees.o: deflate.h zutil.h zlib.h zconf.h trees.h
+#uncompr.o: zlib.h zconf.h
+#zutil.o: zutil.h zlib.h zconf.h
 
-adler32.o: zlib.h zconf.h
-compress.o: zlib.h zconf.h
-crc32.o: crc32.h zlib.h zconf.h
-deflate.o: deflate.h zutil.h zlib.h zconf.h
-example.o: zlib.h zconf.h
-gzio.o: zutil.h zlib.h zconf.h
-inffast.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
-inflate.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
-infback.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
-inftrees.o: zutil.h zlib.h zconf.h inftrees.h
-minigzip.o: zlib.h zconf.h
-trees.o: deflate.h zutil.h zlib.h zconf.h trees.h
-uncompr.o: zlib.h zconf.h
-zutil.o: zutil.h zlib.h zconf.h
+include ../Makefile.inc
+
+$(call ADDDEPENDENCIES,libz_OBJECTS,zlib.h zconf.h)
+$(call ADDDEPENDENCIES,deflate.o gzio.o inffast.o inflate.o infback.o inftrees.o trees.o zutil.o,zutil.h)
+$(call ADDDEPENDENCIES,deflate.o trees.o,deflate.h)
+$(call ADDDEPENDENCIES,inffast.o inflate.o infback.o inftrees.o,inftrees.h)
+$(call ADDDEPENDENCIES,inffast.o inflate.o infback.o,inflate.h inffast.h)
+$(call ADDDEPENDENCIES,crc32.o,crc32.h)
+
