Synchronize on NetBSD-CVS (2013/12/1 12:00:00 UTC)
 - Fix for possible unset uid/gid in toproto
 - Fix for default mtree style
 - Update libelf
 - Importing libexecinfo
 - Resynchronize GCC, mpc, gmp, mpfr
 - build.sh: Replace params with show-params.
     This has been done as the make target has been renamed in the same
     way, while a new target named params has been added. This new
     target generates a file containing all the parameters, instead of
     printing it on the console.
 - Update test48 with new etc/services (Fix by Ben Gras <ben@minix3.org)
     get getservbyport() out of the inner loop

Change-Id: Ie6ad5226fa2621ff9f0dee8782ea48f9443d2091

diff --git a/external/bsd/file/file2netbsd b/external/bsd/file/file2netbsd
--- a/external/bsd/file/file2netbsd
+++ b/external/bsd/file/file2netbsd
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-#	$NetBSD: file2netbsd,v 1.3 2012/02/22 17:47:25 christos Exp $
+#	$NetBSD: file2netbsd,v 1.5 2013/01/04 15:34:47 christos Exp $
 #
 # Copyright (c) 2003, 2011 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -41,7 +41,13 @@ then
 fi
 FILE="$1"
 
-file_vers="$(awk -F', ' '/AC_INIT\(/ { print $2 }' "$FILE/configure.ac")"
+file_vers="$(awk -F',' '/AC_INIT\(/ { print $2 }' "$FILE/configure.ac" | tr -d '[' | tr -d ']' | tr -d ' ')"
+
+case $file_vers in
+[0-9].[0-9][0-9]) ;;
+*)	echo "$PROG: Cannot determine file version: $file_vers" 1>&2
+	exit 1;;
+esac
 
 ### Wipe out stuff we don't want
 find "$FILE" -name .cvsignore -delete
@@ -67,9 +73,9 @@ mv /tmp/file3$$ $c && echo did source mods for $c
 done
 
 #### Move files to proper names
-mv -f doc/file.man doc/file.1
-mv -f doc/libmagic.man doc/libmagic.3
-mv -f doc/magic.man doc/magic.5
+mv -f $FILE/doc/file.man $FILE/doc/file.1
+mv -f $FILE/doc/libmagic.man $FILE/doc/libmagic.3
+mv -f $FILE/doc/magic.man $FILE/doc/magic.5
 
 #### Add RCS tags to man pages
 find "$FILE" -type f -name '*.[0-9]' -print | while read m; do
@@ -86,7 +92,7 @@ mv /tmp/file4$$ $m && echo did manpage mods for $m
 done
 
 #### de-"capsize" the magdir
-mv magic/Magdir magic/magdir
+mv $FILE/magic/Magdir $FILE/magic/magdir
 
 #### Make building easier, don't build magic and doc
 echo '/^SUBDIRS/
